### ISSUE TITLE
EAPOL data not found in latest version but works in 1.2 rc4

### ISSUE THREAD

**Issue by bojangles9** [aircrack-ng/aircrack-ng#2169] opened 2020-07-28 02:53 UTC
**REMOVE ALL OF THE ABOVE TEXT**

# Issue type
- Defect - Unexpected behavior (obvious or confirmed in the forum)

# System information

- OS: Ubuntu 20.04 and Kali Linux
- CPU: Ryzen 3900x
- Wireless card and chipset (if relevant):

# Aircrack-ng version

- Version:
./aircrack-ng --help
  Aircrack-ng 1.6 rev cd77600e - (C) 2006-2020 Thomas d'Otreppe
**AND**
aircrack-ng 
  Aircrack-ng 1.6  - (C) 2006-2020 Thomas d'Otreppe

- Commit Revision hash:

# Defect
WPA handshake is found in attached cap file in Aircrack 1.2 rc4, but not in previously mentioned versions
## How to reproduce the issue

aircrack-ng test.cap
Packets contained no EAPOL data; unable to process this AP. (0 handshake)

Running the same command on Aircrack 1.2 rc4 works.

**Comment by jbenden** [comment] 2020-07-28 08:38
This capture has 4-way EAPOL frames 2, 3, and 4. It does not have the first, M1, which has the starting "replay counter" value (the code sets this field from this M1). Next, the replay counter is a couple of values; not really the same or always increasing - I am unsure how this should be handled....

If I apply the following patch, it is able to proceed:

```
diff --git a/src/aircrack-ng/aircrack-ng.c b/src/aircrack-ng/aircrack-ng.c
index f6701110..afc9a8d3 100644
--- a/src/aircrack-ng/aircrack-ng.c
+++ b/src/aircrack-ng/aircrack-ng.c
@@ -1603,7 +1603,7 @@ skip_station:
        if ((h80211[z + 6] & 0x08) != 0 && (h80211[z + 6] & 0x40) == 0
                && (h80211[z + 6] & 0x80) == 0
                && (h80211[z + 5] & 0x01) != 0
-               && st_cur->wpa.replay == replay_counter)
+               && st_cur->wpa.replay <= replay_counter)
        {
                if (memcmp(&h80211[z + 17], ZERO, sizeof(st_cur->wpa.snonce)) != 0)
                {
@@ -1670,7 +1670,7 @@ skip_station:
        if ((h80211[z + 6] & 0x08) != 0 && (h80211[z + 6] & 0x40) != 0
                && (h80211[z + 6] & 0x80) != 0
                && (h80211[z + 5] & 0x01) != 0
-               && st_cur->wpa.replay == replay_counter)
+               && st_cur->wpa.replay <= replay_counter)
        {
                st_cur->wpa.found |= 1 << 3;
```

@Mister-X- Is this patch correct? Or is there a different problem occurring?

Best regards,
-Joe

**Comment by jbenden** [comment] 2020-07-28 21:01
In reading the spec (802.11i-2004), it seems the replay counter **must** be the same between messages 1 & 2.

Next, replay counter should be larger than that stored from M1/M2 in messages 3 & 4. And it should match between 3 & 4.

I am working on a fix...
-Joe

@Mister-X- Nevermind, I found the needed spec.

**Comment by jbenden** [comment] 2020-07-28 21:10
@renoir789 May I add this PCAP into the unit tests? I want to ensure that it is OK, before doing so. I'd also need to know the passphrase too.

**Comment by ZerBea** [comment] 2020-07-29 13:24
@jbenden correct
M1 and M2 must have the same replaycounter value,
M3 and M4 must have the same replaycounter value,
M3 replaycounter value = M2 replaycounter value +1

But do not trust in the replaycounter, especially when an EAPOL frame received out of EAPOLTIME limit or aireplay-ng destroyed the EAPOL timer of the AP due to transmitting too many disauthentications!
Not every AP increase the replaycounter. Instead the AP increase last byte of the ANONCE (either big endian or little endian dependent on the router architecture)! Please notice: some AP increment replaycounter and last byte of the ANONCE!
Result can be M1 RC0 from first authentication sequence M2 RC0 from second authentication sequence.
aircrack-ng will not be able to recover the PSK due to missing nonce error correction function.
https://community.cisco.com/t5/wireless-mobility-documents/eap-timers-on-wireless-lan-controllers/ta-p/3122477


BTW:
This issue report is a dupe of that:
https://github.com/aircrack-ng/aircrack-ng/issues/2136

**Comment by ZerBea** [comment] 2020-07-29 14:43
Please let me give you an example (cleaned with wpaclean, a realy dangerous tool):
```
$ ./wpaclean clean.cap testnetwork.pcap
Pwning testnetwork.pcap (1/1 100%)
Net 34:81:c4:e7:99:1b TEST_NETWORK
Done
```
wpaclean doesn't detect the correct EAPOL message (aircrack-ng, airodump-ng and besside-ng running the same logic and doesn't detect it, too). 
```
$ ./aircrack-ng -w wordlist clean.cap

                        Aircrack-ng 1.6 rev 1de8fb71

      [00:00:00] 1/1 keys tested (25.67 k/s) 

      Time left: --

                                KEY NOT FOUND


      Master Key     : 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
                       00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 

      Transient Key  : 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
                       00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
                       00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
                       00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 

      EAPOL HMAC     : 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 

```
That lead to an unrecoverable message pair for aircrack-ng.
```
$ tshark -r clean.cap  -T fields -e frame.number -e frame.time
1	Jul 29, 2020 16:05:15.079689000 CEST
2	Jul 29, 2020 16:05:15.062198000 CEST
3	Jul 29, 2020 16:05:15.079689000 CEST
```
In addition to a false EAPOL MESSAGE PAIR (don't trust the RC), the timestamps are completely destroyed and additional messages are removed. That makes it hard to recover the PSK by automatic mode.
hcxpcapngtool will confirm this:
```
$ hcxpcapngtool -o test.22000 clean.cap
reading from clean.cap...

summary capture file
--------------------
file name................................: clean.cap
version (pcap/cap).......................: 2.4 (very basic format without any additional information)
timestamp minimum (GMT)..................: 29.07.2020 16:05:15
timestamp maximum (GMT)..................: 29.07.2020 16:05:15
used capture interfaces..................: 1
link layer header type...................: DLT_IEEE802_11 (105)
endianess (capture system)...............: little endian
packets inside...........................: 3
BEACON (total)...........................: 1
EAPOL messages (total)...................: 2
EAPOL RSN messages.......................: 2
ESSID (total unique).....................: 1
EAPOLTIME gap (measured maximum usec)....: 17491
EAPOL ANONCE error corrections (NC)......: not detected
EAPOL M1 messages (total)................: 1
EAPOL M2 messages (total)................: 1
EAPOL pairs (total)......................: 1
EAPOL pairs (best).......................: 1
EAPOL pairs written to combi hash file...: 1 (RC checked)
EAPOL M12E2 (challenge)..................: 1

Warning: out of sequence timestamps!
This dump file contains frames with out of sequence timestamps.

Warning: missing frames!
This dump file contains no undirected proberequest frames.
An undirected proberequest may contain information about the PSK.
It always happens if the capture file was cleaned or
it could happen if filter options are used during capturing.
That makes it hard to recover the PSK.

Warning: missing frames!
This dump file contains no important frames like
authentication, association or reassociation.
It always happens if the capture file was cleaned or
it could happen if filter options are used during capturing.
That makes it hard to recover the PSK.

Warning: missing frames!
This dump file doesn't contain enough EAPOL M1 frames.
It always happens if the capture file was cleaned or
it could happen if filter options are used during capturing.
That makes it impossible to calculate nonce-error-correction values.
```
many warnings appeared, but the MESSAGE PAIR is converted to a hash line, hashcat understand.
Due to missing frames and destroyed timestamps, hashcat require additional options (NC=8) to recover the PSK:
```
$ hashcat -m 22000 --nonce-error-corrections=8 test.22000 wordlist
                                                 
Session..........: hashcat
Status...........: Cracked
Hash.Name........: WPA-PBKDF2-PMKID+EAPOL
Hash.Target......: test.22000
Time.Started.....: Wed Jul 29 16:27:26 2020 (1 sec)
Time.Estimated...: Wed Jul 29 16:27:27 2020 (0 secs)
Guess.Base.......: File (wordlist)
Guess.Queue......: 1/1 (100.00%)
Speed.#1.........:       41 H/s (0.71ms) @ Accel:8 Loops:128 Thr:1024 Vec:1
Recovered........: 1/1 (100.00%) Digests
Progress.........: 1/1 (100.00%)
Rejected.........: 0/1 (0.00%)
Restore.Point....: 0/1 (0.00%)
Restore.Sub.#1...: Salt:0 Amplifier:0-1 Iteration:0-1
Candidates.#1....: 12345678 -> 12345678
Hardware.Mon.#1..: Temp: 64c Fan: 49% Util: 54% Core:1860MHz Mem:5005MHz Bus:16

6c2d235b40033ffb845759f15dfc335f:3481c4e7991b:0c9d92b486ca:TEST_NETWORK:12345678

Started: Wed Jul 29 16:27:23 2020
Stopped: Wed Jul 29 16:27:27 2020
```
I'm running new hash mode 22000 to recover the PSK, because hccapx and 16800 are outdated.

Attached cap file to reproduce this issue:
M1M2 
[clean.cap.zip](https://github.com/aircrack-ng/aircrack-ng/files/4995477/clean.cap.zip)

M2M3 for testing after applying the patch:
[clean2.cap.zip](https://github.com/aircrack-ng/aircrack-ng/files/4996053/clean2.cap.zip)
expected result: aircrack-ng is not able to recover the PSK.

**Comment by ZerBea** [comment] 2020-07-29 15:02
BTW:
The attached original cap file test.zip is showing the same issue:

```
$ tshark -r test.cap  -T fields -e frame.number -e frame.time
...
10	Dec 17, 2019 16:10:55.951287000 CET
11	Dec 17, 2019 16:10:55.951280000 CET
...
33	Dec 17, 2019 16:10:55.964599000 CET
34	Dec 17, 2019 16:10:55.964593000 CET
...
1584	Dec 17, 2019 16:11:11.162315000 CET
1585	Dec 17, 2019 16:11:11.162313000 CET
```
and more...

```
$ hcxpcapngtool test.cap
reading from test.cap...

summary capture file
--------------------
file name................................: test.cap
version (pcap/cap).......................: 2.4 (very basic format without any additional information)
timestamp minimum (GMT)..................: 17.12.2019 16:10:53
timestamp maximum (GMT)..................: 17.12.2019 16:11:12
used capture interfaces..................: 1
link layer header type...................: DLT_IEEE802_11 (105)
endianess (capture system)...............: little endian
packets inside...........................: 1617
BEACON (total)...........................: 1
ACTION (total)...........................: 5
PROBERESPONSE............................: 3
ASSOCIATIONREQUEST (total)...............: 1
ASSOCIATIONREQUEST (PSK).................: 1
WPA encrypted............................: 31
EAPOL messages (total)...................: 3
EAPOL RSN messages.......................: 3
ESSID (total unique).....................: 1
EAPOLTIME gap (measured maximum usec)....: 14337
EAPOL ANONCE error corrections (NC)......: not detected
EAPOL M2 messages (total)................: 1
EAPOL M3 messages (total)................: 1
EAPOL M4 messages (total)................: 1
EAPOL pairs (total)......................: 1
EAPOL pairs (best).......................: 1
EAPOL M32E2 (authorized).................: 1

Warning: out of sequence timestamps!
This dump file contains frames with out of sequence timestamps.

Warning: missing frames!
This dump file contains no undirected proberequest frames.
An undirected proberequest may contain information about the PSK.
It always happens if the capture file was cleaned or
it could happen if filter options are used during capturing.
That makes it hard to recover the PSK.

Warning: missing frames!
This dump file doesn't contain enough EAPOL M1 frames.
It always happens if the capture file was cleaned or
it could happen if filter options are used during capturing.
That makes it impossible to calculate nonce-error-correction values.
```

**Comment by ZerBea** [comment] 2020-07-29 21:27
Now let's put all issues together:
running against the cleaned cap:
```
$ ./wpaclean clean3.cap test3.pcap
Pwning test3.pcap (1/1 100%)
Net 34:81:c4:e7:99:1b TEST_NETWORK
Done

$ ./aircrack-ng -w wordlist clean3.cap
Reading packets, please wait...
Opening clean3.cap
Read 3 packets.

   #  BSSID              ESSID                     Encryption

   1  34:81:C4:E7:99:1B  TEST_NETWORK              WPA (1 handshake)

Choosing first network as target.

Reading packets, please wait...
Opening clean3.cap
Read 3 packets.

1 potential targets



                         Aircrack-ng 1.6 rev 1de8fb71

      [00:00:00] 1/1 keys tested (23.43 k/s) 

      Time left: --

                                KEY NOT FOUND


      Master Key     : 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
                       00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 

      Transient Key  : 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
                       00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
                       00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
                       00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 

      EAPOL HMAC     : 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
```

running against the original pcap
```
$ ./aircrack-ng -w wordlist test3.pcap
Reading packets, please wait...
Opening test3.pcap
Read 4 packets.

   #  BSSID              ESSID                     Encryption

   1  34:81:C4:E7:99:1B  TEST_NETWORK              WPA (1 handshake)

Choosing first network as target.

Reading packets, please wait...
Opening test3.pcap
Read 4 packets.

1 potential targets



                         Aircrack-ng 1.6 rev 1de8fb71

      [00:00:00] 1/1 keys tested (27.36 k/s) 

      Time left: --

                                KEY NOT FOUND


      Master Key     : 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
                       00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 

      Transient Key  : 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
                       00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
                       00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
                       00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 

      EAPOL HMAC     : 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
```
As you can see, it is not enough to verify the replaycount only.
Disregarding EAPOLTIME will lead to unrecoverable message pairs.
Disregarding ANONCE increment will lead to unrecoverable message pairs.
False timestamps will lead to unrecoverable message pairs.

Attached the example cap files:
[test3.zip](https://github.com/aircrack-ng/aircrack-ng/files/4997546/test3.zip)

BTW:
The PSK from this example is not recoverable and hcxpcapngtool will not convert it:
```
$ hcxpcapngtool -o test.22000 clean3.cap
reading from clean3.cap...

summary capture file
--------------------
file name................................: clean3.cap
version (pcap/cap).......................: 2.4 (very basic format without any additional information)
timestamp minimum (GMT)..................: 29.07.2020 16:05:15
timestamp maximum (GMT)..................: 29.07.2020 16:05:45
used capture interfaces..................: 1
link layer header type...................: DLT_IEEE802_11 (105)
endianess (capture system)...............: little endian
packets inside...........................: 3
BEACON (total)...........................: 1
EAPOL messages (total)...................: 2
EAPOL RSN messages.......................: 2
ESSID (total unique).....................: 1
EAPOLTIME gap (measured maximum usec)....: 30614331
EAPOL ANONCE error corrections (NC)......: not detected
EAPOL M1 messages (total)................: 1
EAPOL M2 messages (total)................: 1

Warning: out of sequence timestamps!
This dump file contains frames with out of sequence timestamps.

Warning: missing frames!
This dump file contains no undirected proberequest frames.
An undirected proberequest may contain information about the PSK.
It always happens if the capture file was cleaned or
it could happen if filter options are used during capturing.
That makes it hard to recover the PSK.

Warning: missing frames!
This dump file contains no important frames like
authentication, association or reassociation.
It always happens if the capture file was cleaned or
it could happen if filter options are used during capturing.
That makes it hard to recover the PSK.

Warning: missing frames!
This dump file doesn't contain enough EAPOL M1 frames.
It always happens if the capture file was cleaned or
it could happen if filter options are used during capturing.
That makes it impossible to calculate nonce-error-correction values.
```

**Comment by jbenden** [comment] 2020-07-30 22:20
@ZerBea Thank you for all the detailed information. It **is** appreciated.

With the changes currently on the linked PR, the following has been accomplished:

- Airodump-ng now saves PCAPs with correct timestamps (in usecs.)
- Aircrack-ng properly decodes all test files's 4-way handshakes; and ends up finding the passphrase.
- Aircrack-ng now seems to convert to HCCAP formats OK. No code changes here, so it must be 4-way handshake related.
- Added two extra unit-tests for ensuring 4-way handshake detection continues to work.

As to the other tools; wpaclean & besside-ng & others: While I could enumerate the problems with them, I'll skip that for now. These tools are in an extremely bad condition.

Best regards,
-Joe

@ZerBea Would you mind testing the PR to confirm?

**Comment by ZerBea** [comment] 2020-08-02 20:08
@jbenden, hi Joe.
No problem. I'm back home, tomorrow. Than I'll start some more tests.
aircrack-ng is the leading and major penetration testing tool and it is really good to see the fixes and progress. Since the good old days (moving from wep to wpa1 and later on to wpa2) many, many things changed.
I analyzed several cap files (wpa-sec - most submitted cap files are captured by aircrack-ng suite) and noticed that we can't trust the replaycounter. Some VENDOR increment ANONCE, instead of the replaycounter (or both of them). 
In addition to that, I talked with kimo and we noticed, that you even can't trust the driver (timestamp), too.

BTW:
the gcc 10 commit is working like a charm - good job.

Cheers
Mike

**Comment by ZerBea** [comment] 2020-08-03 08:52
@jbenden , hi Joe. It works only partly.
I applied the patch and noticed that the detection of handshakes does't work as expected. We take the example test3.zip
```

$ ./aircrack-ng test3.pcap -j test
Reading packets, please wait...
Opening test3.pcap
Read 4 packets.

   #  BSSID              ESSID                     Encryption

   1  34:81:C4:E7:99:1B  TEST_NETWORK              WPA (1 handshake)

Choosing first network as target.

Reading packets, please wait...
Opening test3.pcap
Read 4 packets.

1 potential targets



Building Hashcat (3.60+) file...

[*] ESSID (length: 12): TEST_NETWORK
[*] Key version: 2
[*] BSSID: 34:81:C4:E7:99:1B
[*] STA: 0C:9D:92:B4:86:CA
[*] anonce:
    B6 60 E4 0E D1 BC 06 69 0F 05 67 24 74 3A E5 1E 
    68 FF 29 4B 85 43 AB B4 60 11 EC FA 98 30 DD 8D 
[*] snonce:
    D8 BE E7 C6 BD 6B 90 F7 E8 2D D6 05 D5 E1 F1 14 
    A7 54 C1 C7 CA 3B 9D B9 AC DD 71 EC 6C 73 53 16 
[*] Key MIC:
    96 39 E1 C0 1C 11 D3 A0 13 4E BA 77 91 25 A5 6F
[*] eapol:
    01 03 00 75 02 01 0A 00 00 00 00 00 00 00 00 00 
    01 D8 BE E7 C6 BD 6B 90 F7 E8 2D D6 05 D5 E1 F1 
    14 A7 54 C1 C7 CA 3B 9D B9 AC DD 71 EC 6C 73 53 
    16 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
    00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
    00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
    00 00 16 30 14 01 00 00 0F AC 04 01 00 00 0F AC 
    04 01 00 00 0F AC 02 80 00 

Successfully written to test.hccapx
```
This are the values of the converted messagepair:
$ wlanhcxinfo -i test.hccapx -A -S -R
ANONCE:SNONCE:RC
b660e40ed1bc06690f056724743ae51e68ff294b8543abb46011ecfa9830dd8d:d8bee7c6bd6b90f7e82dd605d5e1f114a754c1c7ca3b9db9acdd71ec6c735316:0000000000000001

Now, please take a look at the timestamps from the packets 2 and 3
2	Jul 29, 2020 16:05:15.062198000 CEST
3	Jul 29, 2020 16:05:45.676529000 CEST

aircrack-ng converted a messagepair that has a timegap from 30 seconds. The PSK from test.hccapx is not recoverable, because the converted messagepair is out of the EAPOLTIME.
Neither aircrack-ng nor hashcat nor JtR is able to recover the PSK from this messagepair.

So, your patch works only partly:
Yes, because M2M3 are converted, now
No, because the PSK from the converted messagepair is not recoverable and aircrack-ng will waste time while trying to recover the PSK from an uncrackable messagepair.

To solve this, you have to refactor the whole logic.
Search for matching replaycounts M1RC == M2RC or M2RC == M3RC+1 or M3RC == M4RC (not zeroed) or M1RC == M4RC +1 (not zeroed)
Than search for the lowest timegap between and M1M2, M2M3, M3M4 (not zeroed M4) or M1M4.
Now convert this messagepair (matching RC + lowest timegap between EAPOL messages) to hccapx or feed it to aircrack-ng cracker logic.

Additional you can try to add nonce error correction logic to compensate packet loss. Therefore validate ANONCEs:
```
b660e40ed1bc06690f056724743ae51e68ff294b8543abb46011ecfa9830dd8a
b660e40ed1bc06690f056724743ae51e68ff294b8543abb46011ecfa9830dd8b
b660e40ed1bc06690f056724743ae51e68ff294b8543abb46011ecfa9830dd8c
b660e40ed1bc06690f056724743ae51e68ff294b8543abb46011ecfa9830dd8d
b660e40ed1bc06690f056724743ae51e68ff294b8543abb46011ecfa9830dd8e
b660e40ed1bc06690f056724743ae51e68ff294b8543abb46011ecfa9830dd8f
b660e40ed1bc06690f056724743ae51e68ff294b8543abb46011ecfa9830dd90
```

In that case, the PSK is recoverable with NC 7. That means you have to feed aircrack-ng with the following messagepairs:
```
b660e40ed1bc06690f056724743ae51e68ff294b8543abb46011ecfa9830dd8a:d8bee7c6bd6b90f7e82dd605d5e1f114a754c1c7ca3b9db9acdd71ec6c735316
b660e40ed1bc06690f056724743ae51e68ff294b8543abb46011ecfa9830dd8b:d8bee7c6bd6b90f7e82dd605d5e1f114a754c1c7ca3b9db9acdd71ec6c735316
b660e40ed1bc06690f056724743ae51e68ff294b8543abb46011ecfa9830dd8c:d8bee7c6bd6b90f7e82dd605d5e1f114a754c1c7ca3b9db9acdd71ec6c735316
b660e40ed1bc06690f056724743ae51e68ff294b8543abb46011ecfa9830dd8d:d8bee7c6bd6b90f7e82dd605d5e1f114a754c1c7ca3b9db9acdd71ec6c735316
b660e40ed1bc06690f056724743ae51e68ff294b8543abb46011ecfa9830dd8e:d8bee7c6bd6b90f7e82dd605d5e1f114a754c1c7ca3b9db9acdd71ec6c735316
b660e40ed1bc06690f056724743ae51e68ff294b8543abb46011ecfa9830dd8f:d8bee7c6bd6b90f7e82dd605d5e1f114a754c1c7ca3b9db9acdd71ec6c735316
b660e40ed1bc06690f056724743ae51e68ff294b8543abb46011ecfa9830dd90:d8bee7c6bd6b90f7e82dd605d5e1f114a754c1c7ca3b9db9acdd71ec6c735316
```
You will not loose too much time, because PBKDF2 has to be done only once for this messagepairs.
Doing this, aircrack-ng will be able to recover the PSK from this example: clean.cap.zip

Explanation:
airodump-ng is a passive dumper. It is neither able to detect a packet loss, nor to request lost packets. Please compare with hcxdumptool: here we request the missing EAPOL message, until we are able to calculate a valid messagepair!
aireplay-ng is a fine deauther. Unfortunately it is neither able to detect a packet loss, nor to request lost packets. Additional it destroys the EAPOLTIME of an AP, when transmitting too much deauthentications.

BTW:
If airodump-ng is capturing with BSSID option all(!) proberequests from CLIENTs, running MAC_RANDOMIZATION are filtered out. Unfortunately, many, many of this requests will contain a PSK in the clear. The same applies to EAPOL ID requests.
Please do not filter them out.


aircrack-ng suite is a great set of tools. Unfortunately the logic (attacking, detection, conversion) behind the scene is very old. That was the major reason for me to leave this suite and to code hcxtools(hcxdumptool.

Cheers
Mike

**Comment by jbenden** [comment] 2020-08-03 20:57
@ZerBea  So, does the test3.cap even have a viable solution? Or is it simply not salvageable? I am thinking it isn't, based on what was said with timeout values between EAPOL messages. [So, keeping track of time intervals could offer a stop-gap fix for the current code; ie. it wouldn't think this PCAP works.]

Thanks for everything!
-Joe

**Comment by jbenden** [comment] 2020-08-03 21:53
@ZerBea I have modified the logic to include timeouts. It's very messy and is only a solution to the current code state...

**Comment by ZerBea** [comment] 2020-08-03 21:57
@jbenden you're absolutely right.
test3.cap is incomplete due to packet loss. The capture device is too far away from AP and CLIENT. Unfortunately aircarck-ng doesn't notice that and try to recover the PSK. Unfortunately it convert this messagepair to hccap/hccapx. At this time, we have an invalid messagepair from which that hascat can't recover the PSK.
So, your first solution is good (M1RC = M2RC, M2RC = M3RC+1, M3RC = M4RC (not zeroed), M1RC = M4RC +1 (not zeroed).
But it will produce invalid results.

**Comment by ZerBea** [comment] 2020-08-03 21:58
Every solution that include timeouts is a good solution. Great that you included this.
To get a feeling of this EAPOLTIME, please take a look at hcxdumptool time response behavior.
```
$ sudo hcxdumptool -i wlp39s0f3u1u1u2 --enable_status=1 -c 8
initialization...

start capturing (stop with ctrl+c)
NMEA 0183 SENTENCE........: N/A
INTERFACE NAME............: wlp39s0f3u1u1u2
INTERFACE HARDWARE MAC....: aca213117f56
DRIVER....................: mt7601u
DRIVER VERSION............: 5.7.11-arch1-1
DRIVER FIRMWARE VERSION...: N/A
ERRORMAX..................: 100 errors
BPF code blocks...........: 0
FILTERLIST ACCESS POINT...: 0 entries
FILTERLIST CLIENT.........: 0 entries
FILTERMODE................: unused
WEAK CANDIDATE............: 12345678
ESSID list................: 0 entries
ROGUE (ACCESS POINT)......: 00cb00b6f912 (BROADCAST HIDDEN)
ROGUE (ACCESS POINT)......: 00cb00b6f913 (BROADCAST OPEN)
ROGUE (ACCESS POINT)......: 00cb00b6f914 (incremented on every new client)
ROGUE (CLIENT)............: b0ece18fc55a
EAPOLTIMEOUT..............: 20000 usec
REPLAYCOUNT...............: 64208
ANONCE....................: d8f668fa59fad76d734979588fe6c3f7e6764b12237c7c090c320a87a265c483
SNONCE....................: 0f5adb4331586f0da1c13781984bd69ceecef0248dfaeaf0d1858a196e66dcab

00:03:53   8 0c9d92b486ca 3481c4e7991b TEST_NETWORK [EAPOL:M1M2ROGUE EAPOLTIME:1601 RC:64208 KDV:2 PSK:12345678]
00:03:54   8 0c9d92b486ca 3481c4e7991b TEST_NETWORK [EAPOL:M1M2 EAPOLTIME:1290 RC:4 KDV:2 PSK:12345678]
00:03:54   8 0c9d92b486ca 3481c4e7991b TEST_NETWORK [EAPOL:M2M3 EAPOLTIME:2046 RC:5 KDV:2 PSK:12345678]
00:03:54   8 0c9d92b486ca 3481c4e7991b TEST_NETWORK [EAPOL:M3M4ZEROED EAPOLTIME:3238 RC:5 KDV:2]
```
This is the captured handshake between AP and CLIENT.
```
00:03:54   8 0c9d92b486ca 3481c4e7991b TEST_NETWORK [EAPOL:M1M2 EAPOLTIME:1290 RC:4 KDV:2 PSK:12345678]
00:03:54   8 0c9d92b486ca 3481c4e7991b TEST_NETWORK [EAPOL:M2M3 EAPOLTIME:2046 RC:5 KDV:2 PSK:12345678]
00:03:54   8 0c9d92b486ca 3481c4e7991b TEST_NETWORK [EAPOL:M3M4ZEROED EAPOLTIME:3238 RC:5 KDV:2]
```
You may have noticed, that we have to be fast (extreme fast) to request an M2 from the CLIENT, before the AP is able to respond:
```
00:03:53   8 0c9d92b486ca 3481c4e7991b TEST_NETWORK [EAPOL:M1M2ROGUE EAPOLTIME:1601 RC:64208 KDV:2 PSK:12345678]
```
Usually we don't need the following handshake between AP and CLIENT, because we got all information to recover the PSK, long before the authentication sequence between them started.

**Comment by jbenden** [comment] 2020-08-03 22:07
@ZerBea Thank you for all of your help!

I'll merge the PR as soon as it clears CI.

**Comment by ZerBea** [comment] 2020-08-03 22:16
Please notice: aircrack-ng suite use 2 tools to force to receive a handshake (airodump-ng and aireplay-ng). Both tools "don't talk" with each other.
Transmitting too many deauthentication frames will destroy the EAPOLTIMER of an AP and it will renew his ANONCE (complete or +1) and/or its RC.
Transmitting a deauthentication frame within an authentication sequence, will cause an AP to renew his ANONCE  (complete or +1) and/or its RC.
Some mobile devices add several additional frames (ACTION frame, NULL frame, BLOCK ACK) to the authentication sequence. That will increase the EAPOLTIME between the messages.
All this (counter) measures taken together, make it hard to get a valid messagepair.

**Comment by ZerBea** [comment] 2020-08-04 07:55
@jbenden sent you a PM, containing some additional information which I don't like to share via git issue report.

Cheers
Mike

**Closed as completed** 2020-08-04 18:51 UTC
