### ISSUE TITLE
counting data with -x option

### ISSUE THREAD

**Issue by aircrack-ng** [aircrack-ng/aircrack-ng#1061] opened 2018-03-10 20:21 UTC
**Reported by anonymous on 15 Dec 2012 22:16 UTC**

it seems that airodump-ng doesen't count data packets when you use the -x option for active probe scanning.

**Comment by gemesa** [comment] 2023-02-18 20:55
Looks like this is the intended behavior:

`ieee80211.h`:
```
...
#define	IEEE80211_FC0_SUBTYPE_DATA		0x00
#define	IEEE80211_FC0_SUBTYPE_PROBE_RESP	0x50
...
```

`airodump-ng.c`:
```
...
	/* skip all non probe response frames in active scanning simulation mode */
	if (lopt.active_scan_sim > 0 && h80211[0] != 0x50) return (0);
...
```

Do we want to change this or close the issue?

**Comment by Mister-X-** [comment] 2023-02-18 21:28
Wording says "it seems", and you showed it's incorrect. So, closing.

Thanks.

**Closed as completed by Mister-X-** 2023-02-18 21:28 UTC
Labels: bug, #airodump-ng, @minor
